In [3]:
# Week 3: NumPy and Pandas for Data Manipulation
# Theory: Study NumPy arrays,operations,broadcasting and Pandas DataFrames,Series,indexing and data grouping.
# Hands-On: Perform operations with NumPy and manipulate datasets with Pandas.
# Client Project: Clean and aggregate a dataset (e.g., remove missing values,calculate averages).
# Submit: Python script and a summary of the concepts learned (on Google Classroom)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**1.Theory: Study NumPy arrays, operations, broadcasting, and Pandas
DataFrames, Series, indexing, and data grouping.**


**Numpy arrays**

- A NumPy array is a powerful n-dimensional array object provided by the NumPy library. 
- Designed for high-performance mathematical and numerical operations.

In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('number of dimension is:',a.ndim) 
print('shape is:',a.shape)     
print('size is:',a.size)      
print('data type is :',a.dtype)
print('item size is:',a.itemsize)  

number of dimension is: 2
shape is: (2, 3)
size is: 6
data type is : int32
item size is: 4


**Operations**

- element-wise operations:

    - Arithmetic: +, -, *, /
    
    - Comparisons: >, <, ==
    
    - Aggregations: sum(), mean(), max(), min()

 **Arithmetic Operations**

In [13]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('addition',a + b)      
print('substraction',a - b)     
print('multiplication',a * b)      
print('division',a / b)     
print('power of the number',a ** 2)   


addition [5 7 9]
substraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]
power of the number [1 4 9]


**Unary Operations**

In [19]:
a=np.array([1, 2, 3])
print(np.sqrt(a))      
print(np.exp(a))       
print(np.log(a))      


[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


**Matrix**

In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))      
print(np.matmul(A, B))      
print(A@B)                
print(np.transpose(A))       
print(np.linalg.inv(A))     
print(np.linalg.det(A))    


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


**Sorting & Searching**

In [24]:
a = np.array([3, 1, 2])
print(np.sort(a))         
print(np.argsort(a))      
print(np.argmax(a))     
print(np.argmin(a))       


[1 2 3]
[1 2 0]
0
1


**Broadcasting**

- Broadcasting is a powerful feature in NumPy that allows arithmetic operations between arrays of different shapes and sizes, without explicitly replicating data.
- It's fast and memory-efficient.
- Two dimensions are compatible if:
    - They are equal, or
    
    - One of them is 1
    
    - When broadcasting, NumPy compares the shapes from right to left.

In [25]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([10, 20, 30])  
print(A + B)


[[11 22 33]
 [14 25 36]]


 **Pandas DataFrames**

- A DataFrame is the core data structure in Pandas, used for handling 2-dimensional, tabular data.

In [28]:
data= {
    'Name': ['Pratipad', 'Tarun', 'Jaggu'],
    'Age': [24, 22, 25],
    'City': ['ODISHA', 'BLS', 'JAGATSINGHPUR']
}
df=pd.DataFrame(data)
print(df)

       Name  Age           City
0  Pratipad   24         ODISHA
1     Tarun   22            BLS
2     Jaggu   25  JAGATSINGHPUR


In [30]:
df = pd.DataFrame({
    'Product': ['Pen', 'Pencil', 'Notebook'],
    'Price': [10, 5, 30]
})
data = [
    {'Name': 'A', 'Score': 90},
    {'Name': 'B', 'Score': 80}
] 
df = pd.DataFrame(data)
import numpy as np
df = pd.DataFrame(np.array([[1, 2], [3, 4]]), columns=['A', 'B'])
df

A  B
0  1  2
1  3  4

 **Series**

- A Series is a one-dimensional labeled array capable of holding data of any type (integer, float, string, Python objects, etc.).
- Think of it as a column in a table or an enhanced version of a Python list or NumPy array.

In [31]:
import pandas as pd
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)


0    10
1    20
2    30
3    40
dtype: int64


In [32]:
sales = pd.Series([100, 200, 300], index=['Jan', 'Feb', 'Mar'])
# Increase all sales by 10%
updated = sales * 1.10
# Filter months with sales > 250
high_sales = updated[updated > 250]
high_sales

Mar    330.0
dtype: float64

- Indexing in Pandas lets you access, slice, modify, and filter data efficiently in Series and DataFrames using labels and positions.

In [33]:
import pandas as pd

s = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
s

a    100
b    200
c    300
dtype: int64

In [34]:
import pandas as pd

data = {
    'Name': ['Pratipad', 'Tarun', 'Jaggu','chintu'],
    'Age': [24, 22, 25,30],
    'City': ['ODISHA', 'BLS', 'JAGATSINGHPUR','KDP']
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print(df)


       Name  Age           City
a  Pratipad   24         ODISHA
b     Tarun   22            BLS
c     Jaggu   25  JAGATSINGHPUR
d    chintu   30            KDP


In [35]:
df['Name']


a    Pratipad
b       Tarun
c       Jaggu
d      chintu
Name: Name, dtype: object

In [41]:
df.loc['b']

Name    Tarun
Age        22
City      BLS
Name: b, dtype: object

In [42]:
df.iloc[2]

Name            Jaggu
Age                25
City    JAGATSINGHPUR
Name: c, dtype: object

**Data Grouping**

- Data grouping in Pandas allows you to split data into groups, apply operations, and then combine the results. 
- It’s mostly used for data aggregation, summarization, and analysis.

In [44]:
# syntax
# df.groupby('column_name')


In [48]:
# example
import pandas as pd
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Finance', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Salary': [50000, 60000, 52000, 65000, 70000, 50000]
}

df = pd.DataFrame(data)
print(df)


  Department Employee  Salary
0         HR    Alice   50000
1         IT      Bob   60000
2         HR  Charlie   52000
3         IT    David   65000
4    Finance      Eva   70000
5         HR    Frank   50000


In [49]:
df.groupby('Department')['Salary'].mean()

Department
Finance    70000.000000
HR         50666.666667
IT         62500.000000
Name: Salary, dtype: float64

In [50]:
df.groupby(['Department', 'Employee'])['Salary'].sum()


Department  Employee
Finance     Eva         70000
HR          Alice       50000
            Charlie     52000
            Frank       50000
IT          Bob         60000
            David       65000
Name: Salary, dtype: int64

In [51]:
df.groupby('Department')['Salary'].agg(['min', 'max', 'mean'])

min    max          mean
Department                            
Finance     70000  70000  70000.000000
HR          50000  52000  50666.666667
IT          60000  65000  62500.000000

In [52]:
df.groupby('Department').size()


Department
Finance    1
HR         3
IT         2
dtype: int64

**2.Hands-On: Perform operations with NumPy and manipulate datasets with
Pandas.**

**NumPy Hands-On Operations**

In [55]:
import numpy as np

# Create arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)         
print("Multiplication:", a * b)  

print("Add scalar:", a + 10)      
print("Mean:", np.mean(a))        
print("Sum:", np.sum(a))          
print("Max:", np.max(a))         


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Add scalar: [11 12 13]
Mean: 2.0
Sum: 6
Max: 3


In [56]:
c = np.array([[1], [2], [3]])
d = np.array([10, 20, 30])

# Broadcasting addition
result = c + d
print("Broadcasting Result:\n", result)


Broadcasting Result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


**Pandas Hands-On Data Manipulation**

In [59]:
import pandas as pd
# Load the dataset
df = pd.read_csv(r"C:\Users\prati\OneDrive\Datafiles\super_store_dataset\SampleSuperstore.csv")
df

Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky   
1       Second Class   Consumer  United States        Henderson    Kentucky   
2       Second Class  Corporate  United States      Los Angeles  California   
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
...              ...        ...            ...              ...         ...   
9989    Second Class   Consumer  United States            Miami     Florida   
9990  Standard Class   Consumer  United States       Costa Mesa  California   
9991  Standard Class   Consumer  United States       Costa Mesa  California   
9992  Standard Class   Consumer  United States       Costa Mesa  California   
9993    Second Class   Consumer  United States      Westminster  California   

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2   
1           42420  South        Furniture       Chairs  731.9400         3   
2           90036   West  Office Supplies       Labels   14.6200         2   
3           33311  South        Furniture       Tables  957.5775         5   
4           33311  South  Office Supplies      Storage   22.3680         2   
...           ...    ...              ...          ...       ...       ...   
9989        33180  South        Furniture  Furnishings   25.2480         3   
9990        92627   West        Furniture  Furnishings   91.9600         2   
9991        92627   West       Technology       Phones  258.5760         2   
9992        92627   West  Office Supplies        Paper   29.6000         4   
9993        92683   West  Office Supplies   Appliances  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200  
9993      0.00   72.9480  

[9994 rows x 13 columns]

In [60]:
# Display first few rows
df.head()

Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164

**Missing Value**

In [61]:
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [62]:
df.describe()

Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [63]:
# Column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Ship Mode     9994 non-null   object 
 1   Segment       9994 non-null   object 
 2   Country       9994 non-null   object 
 3   City          9994 non-null   object 
 4   State         9994 non-null   object 
 5   Postal Code   9994 non-null   int64  
 6   Region        9994 non-null   object 
 7   Category      9994 non-null   object 
 8   Sub-Category  9994 non-null   object 
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64  
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB


In [64]:
# Check duplicated rows
duplicates = df[df.duplicated()]
duplicates

Ship Mode      Segment        Country           City         State  \
950   Standard Class  Home Office  United States   Philadelphia  Pennsylvania   
3406  Standard Class  Home Office  United States       Columbus          Ohio   
3670  Standard Class     Consumer  United States          Salem        Oregon   
4117  Standard Class     Consumer  United States    Los Angeles    California   
4553  Standard Class     Consumer  United States  San Francisco    California   
5905        Same Day  Home Office  United States  San Francisco    California   
6146  Standard Class    Corporate  United States  San Francisco    California   
6334  Standard Class     Consumer  United States  New York City      New York   
6357  Standard Class    Corporate  United States        Seattle    Washington   
7608  Standard Class     Consumer  United States  San Francisco    California   
7735  Standard Class    Corporate  United States        Seattle    Washington   
7759  Standard Class    Corporate  United States        Houston         Texas   
8032     First Class     Consumer  United States        Houston         Texas   
8095    Second Class     Consumer  United States        Seattle    Washington   
9262  Standard Class     Consumer  United States        Detroit      Michigan   
9363  Standard Class  Home Office  United States        Seattle    Washington   
9477    Second Class    Corporate  United States        Chicago      Illinois   

      Postal Code   Region         Category Sub-Category    Sales  Quantity  \
950         19120     East  Office Supplies        Paper   15.552         3   
3406        43229     East        Furniture       Chairs  281.372         2   
3670        97301     West  Office Supplies        Paper   10.368         2   
4117        90036     West  Office Supplies        Paper   19.440         3   
4553        94122     West  Office Supplies        Paper   12.840         3   
5905        94122     West  Office Supplies       Labels   41.400         4   
6146        94122     West  Office Supplies          Art   11.760         4   
6334        10011     East  Office Supplies        Paper   49.120         4   
6357        98103     West  Office Supplies        Paper   25.920         4   
7608        94122     West  Office Supplies        Paper   25.920         4   
7735        98105     West  Office Supplies        Paper   19.440         3   
7759        77041  Central  Office Supplies        Paper   15.552         3   
8032        77041  Central  Office Supplies        Paper   47.952         3   
8095        98115     West  Office Supplies        Paper   12.960         2   
9262        48227  Central        Furniture       Chairs  389.970         3   
9363        98105     West        Furniture  Furnishings   22.140         3   
9477        60653  Central  Office Supplies      Binders    3.564         3   

      Discount   Profit  
950        0.2   5.4432  
3406       0.3 -12.0588  
3670       0.2   3.6288  
4117       0.0   9.3312  
4553       0.0   5.7780  
5905       0.0  19.8720  
6146       0.0   3.1752  
6334       0.0  23.0864  
6357       0.0  12.4416  
7608       0.0  12.4416  
7735       0.0   9.3312  
7759       0.2   5.4432  
8032       0.2  16.1838  
8095       0.0   6.2208  
9262       0.0  35.0973  
9363       0.0   6.4206  
9477       0.8  -6.2370

In [65]:
# drop the country column
df.drop(columns=['Country'], inplace=True)

**Filter Data: Orders from California**

In [66]:
california_orders = df[df['State'] == 'California']
print(california_orders.head())

        Ship Mode    Segment         City       State  Postal Code Region  \
2    Second Class  Corporate  Los Angeles  California        90036   West   
5  Standard Class   Consumer  Los Angeles  California        90032   West   
6  Standard Class   Consumer  Los Angeles  California        90032   West   
7  Standard Class   Consumer  Los Angeles  California        90032   West   
8  Standard Class   Consumer  Los Angeles  California        90032   West   

          Category Sub-Category    Sales  Quantity  Discount   Profit  
2  Office Supplies       Labels   14.620         2       0.0   6.8714  
5        Furniture  Furnishings   48.860         7       0.0  14.1694  
6  Office Supplies          Art    7.280         4       0.0   1.9656  
7       Technology       Phones  907.152         6       0.2  90.7152  
8  Office Supplies      Binders   18.504         3       0.2   5.7825  


**Group By Category and Sum Sales**

In [67]:
category_sales = df.groupby('Category')['Sales'].sum()
category_sales

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

**Top 5 Cities by Profit**

In [68]:
top_cities = df.groupby('City')['Profit'].sum().sort_values(ascending=False).head(5)
print(top_cities)

City
New York City    62036.9837
Los Angeles      30440.7579
Seattle          29156.0967
San Francisco    17507.3854
Detroit          13181.7908
Name: Profit, dtype: float64


**Add a New Column: Profit Margin (%)**

In [69]:
df['ProfitMargin'] = (df['Profit'] / df['Sales']) * 100
print(df[['Sales', 'Profit', 'ProfitMargin']].head())

      Sales    Profit  ProfitMargin
0  261.9600   41.9136         16.00
1  731.9400  219.5820         30.00
2   14.6200    6.8714         47.00
3  957.5775 -383.0310        -40.00
4   22.3680    2.5164         11.25


**Sort by Highest Profit Margin**

In [70]:
high_prof_margin = df.sort_values(by='ProfitMargin', ascending=False)
print(high_prof_margin[['City', 'Sales', 'Profit', 'ProfitMargin']].head())

               City   Sales  Profit  ProfitMargin
2323      Henderson   76.30   38.15          50.0
1708  San Francisco    7.42    3.71          50.0
4578        Hampton  113.10   56.55          50.0
4584       Danville   76.58   38.29          50.0
6463      Baltimore   74.00   37.00          50.0


**3.Client Project: Clean and aggregate a dataset (e.g., remove missing values,
calculate averages).**

**Load the data**

In [74]:
r_df=pd.read_csv(r"C:\Users\prati\OneDrive\Datafiles\Dataset .csv")
r_df

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [75]:
r_df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

**Understand the Data Structure**
- Get column names, datatypes, and non-null count:

In [77]:
r_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  Average Cost for two  9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     9551 non-null   object 
 15  Switch to order menu 

In [79]:
# summary of statistical 
r_df.describe()

Restaurant ID  Country Code    Longitude     Latitude  \
count   9.551000e+03   9551.000000  9551.000000  9551.000000   
mean    9.051128e+06     18.365616    64.126574    25.854381   
std     8.791521e+06     56.750546    41.467058    11.007935   
min     5.300000e+01      1.000000  -157.948486   -41.330428   
25%     3.019625e+05      1.000000    77.081343    28.478713   
50%     6.004089e+06      1.000000    77.191964    28.570469   
75%     1.835229e+07      1.000000    77.282006    28.642758   
max     1.850065e+07    216.000000   174.832089    55.976980   

       Average Cost for two  Price range  Aggregate rating         Votes  
count           9551.000000  9551.000000       9551.000000   9551.000000  
mean            1199.210763     1.804837          2.666370    156.909748  
std            16121.183073     0.905609          1.516378    430.169145  
min                0.000000     1.000000          0.000000      0.000000  
25%              250.000000     1.000000          2.500000      5.000000  
50%              400.000000     2.000000          3.200000     31.000000  
75%              700.000000     2.000000          3.700000    131.000000  
max           800000.000000     4.000000          4.900000  10934.000000

In [83]:
print('The shape of the dataset is : ',r_df.shape)
print('The size of the dataset is : ',r_df.size)
print('The datatype of the dataset is : ',r_df.dtypes)
print('columns of dataset is : ',r_df.columns)

The shape of the dataset is :  (9551, 21)
The size of the dataset is :  200571
The datatype of the dataset is :  Restaurant ID             int64
Restaurant Name          object
Country Code              int64
City                     object
Address                  object
Locality                 object
Locality Verbose         object
Longitude               float64
Latitude                float64
Cuisines                 object
Average Cost for two      int64
Currency                 object
Has Table booking        object
Has Online delivery      object
Is delivering now        object
Switch to order menu     object
Price range               int64
Aggregate rating        float64
Rating color             object
Rating text              object
Votes                     int64
dtype: object
columns of dataset is :  Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost f

**categorical and numerical analysis**

In [86]:
categorical=r_df.select_dtypes(include='object').columns
numerical=r_df.select_dtypes(exclude='object').columns
categorical,numerical


(Index(['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
        'Cuisines', 'Currency', 'Has Table booking', 'Has Online delivery',
        'Is delivering now', 'Switch to order menu', 'Rating color',
        'Rating text'],
       dtype='object'),
 Index(['Restaurant ID', 'Country Code', 'Longitude', 'Latitude',
        'Average Cost for two', 'Price range', 'Aggregate rating', 'Votes'],
       dtype='object'))

**check missing value**

In [81]:
r_df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

**Handle missing value**

In [87]:
import warnings
warnings.filterwarnings('ignore')
c_mode=r_df['Cuisines'].mode()
r_df['Cuisines'].fillna(c_mode.values[0],inplace=True)
r_df

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [89]:
r_df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

**Remove the duplicates**

In [124]:
df_cleaned = r_df.drop_duplicates()
df_cleaned

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

**Aggregation**
- We group the data and calculate averages or totals.

In [125]:
# Example 1: Average by Category
average_df = df_cleaned.groupby(['City','Currency'])['Country Code'].mean().reset_index()
average_df

City            Currency  Country Code
0          Abu Dhabi  Emirati Diram(AED)         214.0
1               Agra  Indian Rupees(Rs.)           1.0
2          Ahmedabad  Indian Rupees(Rs.)           1.0
3             Albany           Dollar($)         216.0
4          Allahabad  Indian Rupees(Rs.)           1.0
..               ...                 ...           ...
136          Weirton           Dollar($)         216.0
137  Wellington City       NewZealand($)         148.0
138   Winchester Bay           Dollar($)         216.0
139          Yorkton           Dollar($)          37.0
140        ��stanbul    Turkish Lira(TL)         208.0

[141 rows x 3 columns]

In [126]:
# AGGREGATION

# Select only numeric columns
numeric_df = df_cleaned.select_dtypes(include='number')

# Combine with the 'City' column for grouping
numeric_df['City'] = df_cleaned['City']

# Group by 'City' and apply mean, sum, and count
agg_all = numeric_df.groupby('City').agg(['mean', 'sum', 'count'])

# Display result
agg_all.head()

Restaurant ID                  Country Code              Longitude  \
                   mean        sum count         mean   sum count       mean   
City                                                                           
Abu Dhabi  8.210826e+06  164216512    20        214.0  4280    20  54.405998   
Agra       3.400166e+06   68003324    20          1.0    20    20  54.622830   
Ahmedabad  7.064363e+06  148351619    21          1.0    21    21  72.531324   
Albany     1.728425e+07  345684945    20        216.0  4320    20 -84.186592   
Allahabad  3.974018e+06   79480368    20          1.0    20    20  61.378793   

                               Latitude  ... Average Cost for two Price range  \
                   sum count       mean  ...                count        mean   
City                                     ...                                    
Abu Dhabi  1088.119968    20  24.464269  ...                   20    3.300000   
Agra       1092.456606    20  19.016683  ...                   20    2.650000   
Ahmedabad  1523.157804    21  23.036910  ...                   21    2.571429   
Albany    -1683.731841    20  31.602963  ...                   20    1.700000   
Allahabad  1227.575863    20  19.089371  ...                   20    2.650000   

                    Aggregate rating                   Votes               
          sum count             mean   sum count        mean    sum count  
City                                                                       
Abu Dhabi  66    20         4.300000  86.0    20  302.250000   6045    20  
Agra       53    20         3.965000  79.3    20  103.100000   2062    20  
Ahmedabad  54    21         4.161905  87.4    21  584.095238  12266    21  
Albany     34    20         3.555000  71.1    20   83.800000   1676    20  
Allahabad  53    20         3.395000  67.9    20   69.600000   1392    20  

[5 rows x 24 columns]

In [127]:
agg_df = df_cleaned.groupby('Rating text').agg({
    'Price range': 'mean',
    'Votes': 'sum'
}).reset_index()
agg_df

Rating text  Price range   Votes
0     Average     1.629917  180307
1   Excellent     2.803987  256383
2        Good     2.138095  481638
3   Not rated     1.235102    1869
4        Poor     1.838710   16873
5   Very Good     2.611677  561575

In [128]:
agg_city = df_cleaned.groupby('City').agg({
    'Average Cost for two': 'mean',
    'Aggregate rating': 'mean'
}).reset_index()
agg_city

City  Average Cost for two  Aggregate rating
0          Abu Dhabi            182.000000          4.300000
1               Agra           1065.000000          3.965000
2          Ahmedabad            857.142857          4.161905
3             Albany             19.750000          3.555000
4          Allahabad            517.500000          3.395000
..               ...                   ...               ...
136          Weirton             25.000000          3.900000
137  Wellington City             71.250000          4.250000
138   Winchester Bay             25.000000          3.200000
139          Yorkton             25.000000          3.300000
140        ��stanbul             81.428571          4.292857

[141 rows x 3 columns]